version: "2"
services:
  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    container_name: php-fpm
    volumes:
      - ./:/var/www
      - ./php.ini-development:/usr/local/etc/php/php.ini
    # environment:
    #   - "DB_PORT=3306"
    #   - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    container_name: webserver
    volumes_from:
      - app
    ports:
      - 8020:80

  #adminer
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8040:8080
  #   environment:
  #     ADMINER_DEFAULT_DB_DRIVER: mysql
  #     ADMINER_DEFAULT_DB_HOST: database
  #     ADMINER_DEFAULT_DB_NAME: homestead
  #     ADMINER_DEFAULT_SERVER: database
  #     ADMINER_DESIGN: nette
  #     ADMINER_PLUGINS: tables-filter tinymce  
  #   depends_on:
  #     - database

  # The Database
  database:
    image: mysql:5.6
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "8030:3306"

volumes:
  dbdata:
